apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy
  namespace: haproxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.0.5-alpine
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy
          name: haproxy-config-volume
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 26999
          name: stats
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 2
          failureThreshold: 2
          tcpSocket:
            port: 1883
      volumes:
      - name: haproxy-config-volume
        configMap:
          name: haproxy-config      